/**
 * Share page — /share/:id
 *
 * SSR: data fetched server-side (no client-side fetch required).
 * No-JS: full HTML render works without JavaScript (pure SSR).
 * Responsive: mobile-first, single column, max-width 600px centered on desktop.
 * Privacy: first name only — no birth date, time, or location.
 */
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

// ─── Types ─────────────────────────────────────────────────────────────────────

interface Prediction {
  id: string;
  domain: string;
  predicted_year_start: number;
  predicted_year_end: number;
  text: string;
  confidence_score: number;
}

interface ShareData {
  first_name: string;
  predictions: Prediction[];
  disclaimer: string;
}

interface Props {
  data: ShareData | null;
  notFound: boolean;
}

// ─── Domain helpers ─────────────────────────────────────────────────────────────

const DOMAIN_ICONS: Record<string, string> = {
  career: '⚡',
  love: '❤',
  health: '🌿',
  finance: '💰',
  family: '🏠',
  other: '◎',
};

// ─── Components ─────────────────────────────────────────────────────────────────

function MilestoneRow({ prediction }: { prediction: Prediction }) {
  const icon = DOMAIN_ICONS[prediction.domain] ?? '◎';
  const yearRange =
    prediction.predicted_year_start === prediction.predicted_year_end
      ? String(prediction.predicted_year_start)
      : `${prediction.predicted_year_start}–${prediction.predicted_year_end}`;
  const pct = Math.round(prediction.confidence_score * 100);

  return (
    <div
      className="milestone-row"
      role="listitem"
      aria-label={`${prediction.domain} — ${yearRange} — ${pct}% confidence`}
      tabIndex={0}
    >
      <span className="milestone-year">{yearRange}</span>
      <div className="milestone-bar-track" role="presentation">
        <div
          className="milestone-bar-fill"
          style={{ width: `${pct}%` }}
          aria-hidden="true"
        />
      </div>
      <span className="milestone-domain" aria-hidden="true">
        {icon}
      </span>
      <span className="milestone-domain-label">
        {prediction.domain.charAt(0).toUpperCase() + prediction.domain.slice(1)}
      </span>
    </div>
  );
}

// ─── Page ───────────────────────────────────────────────────────────────────────

const SharePage: NextPage<Props> = ({ data, notFound }) => {
  if (notFound || !data) {
    return (
      <>
        <Head>
          <title>Timeline not found · JyotishHardev</title>
          <meta name="robots" content="noindex" />
        </Head>
        <main className="page">
          <div className="container">
            <div className="not-found">
              <p className="not-found-text">
                This timeline has been removed.
              </p>
              <a
                href="/"
                className="cta-button"
                aria-label="Generate your own Vedic astrology timeline"
              >
                Generate your own →
              </a>
            </div>
          </div>
        </main>
        <style jsx>{styles}</style>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>{data.first_name}&apos;s Life Timeline · JyotishHardev</title>
        <meta
          name="description"
          content={`${data.first_name}'s Vedic astrology milestone timeline, generated by JyotishHardev.`}
        />
        {/* Social sharing */}
        <meta property="og:title" content={`${data.first_name}'s Life Timeline`} />
        <meta
          property="og:description"
          content="Vedic astrology milestone predictions. Free · No account needed."
        />
        <meta property="og:type" content="website" />
        {/* Prevent search indexing of individual share pages */}
        <meta name="robots" content="noindex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Tiro+Devanagari+Hindi:ital@0;1&display=swap"
          rel="stylesheet"
        />
      </Head>

      {/* Skip to main content */}
      <a className="skip-link" href="#main-content">
        Skip to content
      </a>

      <main id="main-content" className="page">
        <div className="container">
          {/* Header */}
          <header className="page-header">
            <div className="brand">
              <span className="brand-icon" aria-hidden="true">⊕</span>
              <span className="brand-name">JyotishHardev</span>
            </div>
            <h1 className="page-title">
              {data.first_name}&apos;s Life Timeline
            </h1>
            <p className="page-subtitle">
              Generated by Vedic astrology · Personalized milestone predictions
            </p>
          </header>

          {/* Timeline */}
          <section
            aria-label={`${data.first_name}'s milestone timeline`}
            role="list"
            className="timeline"
          >
            {data.predictions.map((prediction) => (
              <MilestoneRow key={prediction.id} prediction={prediction} />
            ))}
          </section>

          {/* Disclaimer */}
          <p className="disclaimer" role="note">
            {data.disclaimer}
          </p>

          {/* CTA */}
          <div className="cta-section">
            <a
              href="/"
              className="cta-button"
              aria-label="Get your own Vedic astrology timeline — free, no account needed"
            >
              Get your own timeline →
            </a>
            <p className="cta-subtext">Free · No account needed</p>
          </div>
        </div>
      </main>

      <style jsx>{styles}</style>
    </>
  );
};

// ─── Styles (CSS-in-JS via styled-jsx) ──────────────────────────────────────────
// No dependency on a CSS framework — works with no-JS/SSR.

const styles = `
  :global(*) {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  :global(body) {
    background-color: #F5F0E8;
    color: #1A1A2E;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 16px;
    line-height: 1.5;
    -webkit-font-smoothing: antialiased;
  }

  .skip-link {
    position: absolute;
    top: -40px;
    left: 0;
    background: #1B1F4A;
    color: white;
    padding: 8px 16px;
    text-decoration: none;
    z-index: 100;
  }
  .skip-link:focus {
    top: 0;
  }

  .page {
    min-height: 100vh;
    padding: 24px 16px 64px;
  }

  .container {
    max-width: 600px;
    margin: 0 auto;
    width: 100%;
  }

  .page-header {
    margin-bottom: 32px;
    text-align: center;
  }

  .brand {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    margin-bottom: 16px;
  }

  .brand-icon {
    font-size: 20px;
    color: #C9A84C;
  }

  .brand-name {
    font-size: 14px;
    color: #6B6B8A;
    font-weight: 500;
    letter-spacing: 0.5px;
  }

  .page-title {
    font-family: 'Tiro Devanagari Hindi', Georgia, serif;
    font-size: 28px;
    color: #1B1F4A;
    margin-bottom: 8px;
    line-height: 1.25;
  }

  @media (min-width: 640px) {
    .page-title {
      font-size: 36px;
    }
  }

  .page-subtitle {
    font-size: 14px;
    color: #6B6B8A;
  }

  .timeline {
    background: #FFFFFF;
    border-radius: 12px;
    padding: 8px 0;
    margin-bottom: 24px;
    box-shadow: 0 2px 8px rgba(27, 31, 74, 0.08);
  }

  .milestone-row {
    display: flex;
    align-items: center;
    padding: 12px 20px;
    border-bottom: 1px solid #E8E2D9;
    gap: 12px;
    cursor: default;
    transition: background-color 200ms ease;
    min-height: 52px;
  }

  .milestone-row:last-child {
    border-bottom: none;
  }

  .milestone-row:focus {
    outline: 2px solid #1B1F4A;
    outline-offset: -2px;
    background: #F5F0E8;
  }

  .milestone-year {
    font-size: 14px;
    color: #1A1A2E;
    font-weight: 600;
    min-width: 72px;
    flex-shrink: 0;
  }

  .milestone-bar-track {
    flex: 1;
    height: 8px;
    background: #E8E2D9;
    border-radius: 4px;
    overflow: hidden;
  }

  .milestone-bar-fill {
    height: 100%;
    background: #C9A84C;
    border-radius: 4px;
    min-width: 8px;
  }

  .milestone-domain {
    font-size: 16px;
    flex-shrink: 0;
  }

  .milestone-domain-label {
    font-size: 12px;
    color: #6B6B8A;
    min-width: 56px;
    flex-shrink: 0;
    text-align: right;
  }

  .disclaimer {
    font-size: 12px;
    color: #6B6B8A;
    text-align: center;
    margin-bottom: 32px;
    line-height: 1.6;
    font-style: italic;
    padding: 0 8px;
  }

  .cta-section {
    text-align: center;
  }

  /* Mobile: sticky CTA at bottom */
  @media (max-width: 640px) {
    .cta-section {
      position: sticky;
      bottom: 0;
      background: #F5F0E8;
      padding: 16px;
      margin: 0 -16px -64px;
      border-top: 1px solid #E8E2D9;
    }
  }

  .cta-button {
    display: inline-block;
    background: #1B1F4A;
    color: #FFFFFF;
    text-decoration: none;
    border-radius: 24px;
    padding: 14px 28px;
    font-size: 16px;
    font-weight: 600;
    width: 100%;
    text-align: center;
    transition: opacity 200ms ease;
  }

  .cta-button:hover {
    opacity: 0.88;
  }

  .cta-button:focus {
    outline: 3px solid #C9A84C;
    outline-offset: 2px;
  }

  @media (min-width: 640px) {
    .cta-button {
      width: auto;
    }
  }

  .cta-subtext {
    margin-top: 8px;
    font-size: 13px;
    color: #6B6B8A;
  }

  .not-found {
    text-align: center;
    padding: 64px 0;
  }

  .not-found-text {
    font-size: 16px;
    color: #6B6B8A;
    margin-bottom: 24px;
  }
`;

// ─── Server-side data fetching ──────────────────────────────────────────────────

export const getServerSideProps: GetServerSideProps<Props> = async (context) => {
  const { id } = context.params ?? {};
  const apiBaseUrl = process.env.API_BASE_URL || 'http://localhost:8000';

  if (!id || Array.isArray(id)) {
    return { props: { data: null, notFound: true } };
  }

  try {
    const response = await fetch(`${apiBaseUrl}/api/v1/share/${id}`, {
      headers: { 'Content-Type': 'application/json' },
      // Server-side fetch — no auth required (public endpoint)
    });

    if (!response.ok) {
      return { props: { data: null, notFound: true } };
    }

    const data: ShareData = await response.json();
    return { props: { data, notFound: false } };
  } catch {
    // Network error — show not-found rather than 500
    return { props: { data: null, notFound: true } };
  }
};

export default SharePage;
